# MoveIt uses this configuration for controller management
trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.01
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - robot1_arm_controller
    - robot1_gripper_controller
    - robot2_arm_controller
    - robot2_gripper_controller

  robot1_arm_controller:
    type: FollowJointTrajectory
    joints:
      - robot1_joint_1
      - robot1_joint_2
      - robot1_joint_3
      - robot1_joint_4
      - robot1_joint_5
      - robot1_joint_6
    action_ns: follow_joint_trajectory
    default: true
  robot1_gripper_controller:
    type: GripperCommand
    joints:
      - robot1_robotiq_85_left_knuckle_joint
    action_ns: gripper_cmd
    default: true
  robot2_arm_controller:
    type: FollowJointTrajectory
    joints:
      - robot2_joint_1
      - robot2_joint_2
      - robot2_joint_3
      - robot2_joint_4
      - robot2_joint_5
      - robot2_joint_6
    action_ns: follow_joint_trajectory
    default: true
  robot2_gripper_controller:
    type: GripperCommand
    joints:
      - robot2_robotiq_85_left_knuckle_joint
    action_ns: gripper_cmd
    default: true